net_params: {L: 4,
             batch_norm: true,
             dropout: 0.1,
             hidden_dim: 256,
             in_feat_dropout: 0.2,
             layer_norm: false,
             mlp_dropout: 0.2,
             n_heads: 8,
             num_atom_features: 36,
             num_edge_input_dim: 76,
             out_dim: 256,
             pos_enc_dim: 20,
             readout: sum,
             residual: true,
             type_loss: MSE}
params: {batch_size: 64,
         ckpt_dir: /content/drive/MyDrive/mlns_project/run/,
         dataname: v2016_LPHIN3f5t_Sp,
         epochs: 300,
         init_lr: 0.0003,
         length_warmup: 65,
         lr_reduce_factor: 0.5,
         lr_schedule_patience: 9,
         min_lr: 5.0e-07,
         path2data: /content/drive/MyDrive/mlns_project/data/,
         seed: 42,
         testflag: test,
         trainflag: train_,
         use_warmup: true,
         valflag: valid,
         weight_decay: 0.0}
